set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g mouse on
run '~/.tmux/plugins/tpm/tpm'

bind-key ! break-pane -d -n _hidden_pane
bind-key @ join-pane -s $.1
